/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoAnTinHoc;

/**
 *
 * @author TRAN PHUC VAN
 */
// Cấu trúc dữ liệu
import java.util.ArrayList;
import java.util.List;
import java.util.Collections;
import java.util.Comparator;
import java.util.function.Predicate;

// Xử lý file
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;


// Giao diện Swing
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;

// Sự kiện
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



public class GiaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GiaoDien.class.getName());
    // Danh sách GPU dùng để hiển thị và xử lý
    private List<GPUClass> danhSach = new ArrayList<>();

    // Cây AVL dùng để lưu và tìm kiếm GPU theo năm phát hành
    private AVLTree<GPUClass> cay = new AVLTree<>((a, b) -> Integer.compare(a.releaseYear, b.releaseYear));

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDoc = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSua1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDoc.setText("Đọc file CSV");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnGhi.setText("Ghi file");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa Card");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm Card");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa Card");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSua1.setText("Cây AVL");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin GPU Theo năm phát hành");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(btnGhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(445, 445, 445))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void ghiFileCSV(File file) {
    
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
        // Ghi dòng tiêu đề
        writer.write("Hãng,Tên,Năm,Dung lượng,Bus,GPU Clock,Mem Clock,Shader,TMU,ROP,Pixel,Vertex,IGP,Bus,Loại RAM,Chip");
        writer.newLine();

        // Ghi từng dòng dữ liệu
        for (GPUClass gpu : danhSach) {
            writer.write(gpu.toCSV());
            writer.newLine();
        }

        JOptionPane.showMessageDialog(this, "Đã ghi file thành công!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi ghi file: " + e.getMessage());
    }
}

    
    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        if (danhSach == null || danhSach.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không có dữ liệu để ghi vào file.");
        return;
    }
        JFileChooser chooser = new JFileChooser();
    int result = chooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        ghiFileCSV(file);
        }
        }//GEN-LAST:event_btnGhiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
   JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));

    JTextField txtManufacturer = new JTextField();
    JTextField txtProductName = new JTextField();
    JTextField txtReleaseYear = new JTextField();
    JTextField txtMemSize = new JTextField();
    JTextField txtMemBusWidth = new JTextField();
    JTextField txtGPUClock = new JTextField();
    JTextField txtMemClock = new JTextField();
    JTextField txtShader = new JTextField();
    JTextField txtTMU = new JTextField();
    JTextField txtROP = new JTextField();
    JTextField txtPixel = new JTextField(); // tùy chọn
    JTextField txtVertex = new JTextField(); // tùy chọn
    JTextField txtIGP = new JTextField(); // Yes/No
    JTextField txtBus = new JTextField();
    JTextField txtMemType = new JTextField();
    JTextField txtChip = new JTextField();

    panel.add(new JLabel("Hãng:")); panel.add(txtManufacturer);
    panel.add(new JLabel("Tên:")); panel.add(txtProductName);
    panel.add(new JLabel("Năm phát hành:")); panel.add(txtReleaseYear);
    panel.add(new JLabel("Dung lượng (MB):")); panel.add(txtMemSize);
    panel.add(new JLabel("Bus Width:")); panel.add(txtMemBusWidth);
    panel.add(new JLabel("GPU Clock:")); panel.add(txtGPUClock);
    panel.add(new JLabel("Mem Clock:")); panel.add(txtMemClock);
    panel.add(new JLabel("Shader:")); panel.add(txtShader);
    panel.add(new JLabel("TMU:")); panel.add(txtTMU);
    panel.add(new JLabel("ROP:")); panel.add(txtROP);
    panel.add(new JLabel("Pixel Shader (tùy chọn):")); panel.add(txtPixel);
    panel.add(new JLabel("Vertex Shader (tùy chọn):")); panel.add(txtVertex);
    panel.add(new JLabel("IGP (Yes/No):")); panel.add(txtIGP);
    panel.add(new JLabel("Bus:")); panel.add(txtBus);
    panel.add(new JLabel("Loại RAM:")); panel.add(txtMemType);
    panel.add(new JLabel("Chip:")); panel.add(txtChip);

    int result = JOptionPane.showConfirmDialog(this, panel, "Thêm GPU mới", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (result == JOptionPane.OK_OPTION) {
        String[] fields = new String[] {
            txtManufacturer.getText(),
            txtProductName.getText(),
            txtReleaseYear.getText(),
            txtMemSize.getText(),
            txtMemBusWidth.getText(),
            txtGPUClock.getText(),
            txtMemClock.getText(),
            txtShader.getText(),
            txtTMU.getText(),
            txtROP.getText(),
            txtPixel.getText(),
            txtVertex.getText(),
            txtIGP.getText(),
            txtBus.getText(),
            txtMemType.getText(),
            txtChip.getText()
        };

        // Kiểm tra rỗng các trường bắt buộc (trừ pixel và vertex: index 10, 11)
        for (int i = 0; i < fields.length; i++) {
            if ((i != 10 && i != 11) && fields[i].trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ các trường bắt buộc.");
                return;
            }
        }

        try {
            GPUClass gpu = new GPUClass(fields);
            danhSach.add(gpu);
            cay.insert(gpu);

            // Hiển thị lại bảng theo thứ tự năm phát hành
            List<GPUClass> sapXepTheoNam = cay.inOrder(); // bạn cần có hàm này trong AVLTree
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            for (GPUClass g : sapXepTheoNam) {
                model.addRow(g.toRow());
            }

            JOptionPane.showMessageDialog(this, "Đã thêm GPU thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tạo GPU: " + e.getMessage());
        }
    }
    
        }//GEN-LAST:event_btnThemActionPerformed

   public void docFileCSV_TuDongCot(File file) {
    danhSach.clear();
    cay = new AVLTree<>((a, b) -> Integer.compare(a.releaseYear, b.releaseYear));

    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        String headerLine = reader.readLine();
        if (headerLine == null || headerLine.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "File CSV không có dòng tiêu đề.");
            return;
        }

        // Tạo cột từ dòng đầu tiên
        String[] columnNames = headerLine.split(",", -1);
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(model);

        // Đọc dữ liệu từng dòng
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) continue;

            String[] fields = line.split(",", -1);
            if (fields.length != columnNames.length) continue;

            model.addRow(fields);

            // Nếu bạn muốn lưu vào danh sách và cây AVL:
            if (fields.length >= 16) {
                GPUClass gpu = new GPUClass(fields);
                danhSach.add(gpu);
                cay.insert(gpu);
            }
        }

        JOptionPane.showMessageDialog(this, "Đã đọc file và tạo bảng thành công!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi đọc file: " + e.getMessage());
    }
}
 
    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        JFileChooser chooser = new JFileChooser();
         int result = chooser.showOpenDialog(this);
         if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        docFileCSV_TuDongCot(file);
        }
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int[] selectedRows = jTable1.getSelectedRows();
    if (selectedRows.length == 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một dòng để xóa.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    List<GPUClass> danhSachCanXoa = new ArrayList<>();

    // Tìm các phần tử cần xóa
    for (int row : selectedRows) {
        String tenCard = model.getValueAt(row, 1).toString();
        String hang = model.getValueAt(row, 0).toString();

        for (GPUClass gpu : danhSach) {
            if (gpu.productName.equals(tenCard) && gpu.manufacturer.equals(hang)) {
                danhSachCanXoa.add(gpu);
                break;
            }
        }
    }

    if (danhSachCanXoa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy phần tử nào để xóa.");
        return;
    }

    // Xóa khỏi danh sách và cây
    for (GPUClass gpu : danhSachCanXoa) {
        danhSach.remove(gpu);
        cay.delete(gpu);
    }

    // Sắp xếp lại danh sách
    Collections.sort(danhSach, (a, b) -> Integer.compare(a.releaseYear, b.releaseYear));

    // Cập nhật lại bảng
    model.setRowCount(0);
    for (GPUClass gpu : danhSach) {
        model.addRow(gpu.toRow());
    }

    JOptionPane.showMessageDialog(this, "Đã xóa " + danhSachCanXoa.size() + " GPU thành công!");
        }//GEN-LAST:event_btnXoaActionPerformed
    
    
    
    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (cay == null || cay.inOrder().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Cây chưa có dữ liệu để phân tích.");
        return;
    }

    cay.phanTichCayTheoNam();    }//GEN-LAST:event_btnSua1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GiaoDien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
