/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.GridLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.Font;
import java.awt.Dimension;


/**
 *
 * @author TRAN PHUC VAN
 */
public class GiaoDienDocFile extends javax.swing.JFrame {
    private AVLTree tree=new AVLTree();

    /**
     * Creates new form GiaoDienDocFile
     */
    public GiaoDienDocFile() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChonFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        bthSua = new javax.swing.JButton();
        btnSapxeptheoTen = new javax.swing.JButton();
        btnSapxeptheoCard = new javax.swing.JButton();
        btnSapxeptheoGPUchip = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Kho Card Đồ họa");

        btnChonFile.setText("Đọc file CSV");
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(table);

        txt1.setEditable(false);

        txt2.setEditable(false);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        bthSua.setText("Sửa");
        bthSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthSuaActionPerformed(evt);
            }
        });

        btnSapxeptheoTen.setText("Sắp xếp theo tên Hãng");
        btnSapxeptheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxeptheoTenActionPerformed(evt);
            }
        });

        btnSapxeptheoCard.setText("Sắp xếp theo tên Card");
        btnSapxeptheoCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxeptheoCardActionPerformed(evt);
            }
        });

        btnSapxeptheoGPUchip.setText("Sắp xếp theo tên GPU chip");
        btnSapxeptheoGPUchip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxeptheoGPUchipActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp theo năm", "Sắp xếp tăng dần", "Sắp xếp giảm dần", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt1)
                            .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bthSua, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSapxeptheoCard, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSapxeptheoGPUchip, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSapxeptheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSapxeptheoCard)
                                    .addComponent(btnSapxeptheoGPUchip))
                                .addGap(18, 18, 18)))
                        .addComponent(btnSapxeptheoTen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bthSua, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File csvFile = fileChooser.getSelectedFile();
        File txtFile = new File("ketqua_docfile.txt");

        try (
            BufferedReader reader = new BufferedReader(new FileReader(csvFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(txtFile))
        ) {
            String line;
            ArrayList<String[]> rows = new ArrayList<>();

            // Đọc dữ liệu từ CSV
            while ((line = reader.readLine()) != null) {
                String[] columns = line.split(",");
                rows.add(columns);
            }

            // Kiểm tra dữ liệu
            if (!rows.isEmpty()) {
                String[] columnNames = rows.get(0); // lấy tiêu đề
                rows.remove(0); // xóa tiêu đề khỏi dữ liệu

                // Hiển thị lên JTable
                String[][] data = new String[rows.size()][columnNames.length];
                for (int i = 0; i < rows.size(); i++) {
                    data[i] = rows.get(i);
                }
                table.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));

                // Ghi ra file TXT
                writer.write(String.join(",", columnNames));
                writer.newLine();
                for (String[] row : data) {
                    writer.write(String.join(",", row));
                    writer.newLine();
                }

                // Khởi tạo cây AVL và chèn dữ liệu
                
                int count = 0;
                for (String[] row : rows) {
                    if (row.length >= 8) {
                        try {
                            GraphicsCard card = new GraphicsCard(row);
                            tree.insert(card);
                            System.out.println("Da chen vao cay: " + card.productName);
                            count++;
                        } catch (Exception e) {
                            System.out.println("loi khi chen: " + e.getMessage());
                        }
                    }
                }
                
                txt1.setText(" Tổng số node đã chèn: " + count);
                
                txt2.setText("Chiều cao cây: "+tree.getHeight());


                JOptionPane.showMessageDialog(this, "Đã ghi ra file TXT: " + txtFile.getAbsolutePath());
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc hoặc ghi file: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        JPanel panel = new JPanel(new GridLayout(0, 2));

    String[] labels = {
        "Manufacturer", "Product Name", "Release Year", "Memory Size",
        "Memory Bus Width", "GPU Clock", "Memory Clock", "Unified Shader",
        "TMU", "ROP", "Pixel Shader", "Vertex Shader",
        "IGP (true/false)", "Bus", "Memory Type", "GPU Chip"
    };

    JTextField[] fields = new JTextField[labels.length];
    for (int i = 0; i < labels.length; i++) {
        panel.add(new JLabel(labels[i] + ":"));
        fields[i] = new JTextField();
        panel.add(fields[i]);
    }

    int result = JOptionPane.showConfirmDialog(this, panel, "Nhập thông tin card đồ họa", JOptionPane.OK_CANCEL_OPTION);
    if (result == JOptionPane.OK_OPTION) {
        try {
            String[] data = new String[labels.length];
            for (int i = 0; i < labels.length; i++) {
                data[i] = fields[i].getText().trim();

                // Kiểm tra bỏ trống (trừ Unified Shader, Pixel Shader, Vertex Shader: chỉ số 7, 10, 11)
                if (i != 7 && i != 10 && i != 11 && data[i].isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" không được bỏ trống!");
                    return;
                }

                // Kiểm tra kiểu int (chỉ số 2 đến 11, trừ 12 là boolean)
                if (!data[i].isEmpty()) {
                        if (i == 3) { // Memory Size
                            try {
                                Double.parseDouble(data[i]);
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" phải là số thực!");
                                return;
                            }
                        } else if (i >= 2 && i <= 11 && i != 3 && i != 12) {
                            try {
                                Integer.parseInt(data[i]);
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" phải là số nguyên!");
                                return;
                            }
                        }
                    }

                // Kiểm tra boolean ở chỉ số 12 (IGP)
                if (i == 12) {
                    if (data[i].equalsIgnoreCase("true")) {
                        data[i] = "Yes";
                    } else if (data[i].equalsIgnoreCase("false")) {
                        data[i] = "No";
                    } else {
                        JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" chỉ được nhập true hoặc false!");
                        return;
                    }
                }

            }

            // Tạo đối tượng GraphicsCard và thêm vào cây
            GraphicsCard card = new GraphicsCard(data);
            //AVLTree tree=new AVLTree();
            tree.insert(card);

            // Thêm vào bảng
            // Sắp xếp lại bảng theo cây AVL
            List<GraphicsCard> danhSachCard = tree.layDanhSachCardTheoNamGiamDan(); // dùng tên tiếng Việt không dấu
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); // xóa toàn bộ dòng cũ

            for (GraphicsCard c : danhSachCard) {
            model.addRow(new Object[] {
                c.manufacturer,
                c.productName,
                c.releaseYear,
                c.memSize,
                c.memBusWidth,
                c.gpuClock,
                c.memClock,
                c.unifiedShader,
                c.tmu,
                c.rop,
                c.pixelShader,
                c.vertexShader,
                c.igp,
                c.bus,
                c.memType,
                c.gpuChip
    });
}


            // Ghi vào file TXT
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("ketqua_docfile.txt", true))) {
                writer.write(String.join(",", data));
                writer.newLine();
            }

            JOptionPane.showMessageDialog(this, "Đã thêm vào cây, bảng và file TXT!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int[] selectedRows = table.getSelectedRows();
    if (selectedRows.length == 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một dòng để xóa!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();

    // Xóa từ dòng cuối lên để tránh lỗi chỉ số
    for (int i = selectedRows.length - 1; i >= 0; i--) {
        int row = selectedRows[i];

        // Lấy releaseYear từ dòng
        String releaseYearStr = model.getValueAt(row, 2).toString().trim();
        try {
            int releaseYear = Integer.parseInt(releaseYearStr);
            tree.delete(releaseYear); // Xóa khỏi cây AVL
            model.removeRow(row);     // Xóa khỏi bảng
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Release Year không hợp lệ ở dòng " + (row + 1));
        }
    }

    // Ghi lại toàn bộ bảng vào file TXT
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("ketqua_docfile.txt"))) {
        for (int i = 0; i < model.getRowCount(); i++) {
            StringBuilder line = new StringBuilder();
            for (int j = 0; j < model.getColumnCount(); j++) {
                line.append(model.getValueAt(i, j).toString());
                if (j < model.getColumnCount() - 1) line.append(",");
            }
            writer.write(line.toString());
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi ghi lại file TXT: " + e.getMessage());
    }

    JOptionPane.showMessageDialog(this, "Đã xóa " + selectedRows.length + " dòng khỏi cây AVL, bảng và file TXT!");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void bthSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthSuaActionPerformed

    int selectedRow = table.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa!");
        return;
    }

    JPanel panel = new JPanel(new GridLayout(0, 2));
    String[] labels = {
        "Manufacturer", "Product Name", "Release Year", "Memory Size",
        "Memory Bus Width", "GPU Clock", "Memory Clock", "Unified Shader",
        "TMU", "ROP", "Pixel Shader", "Vertex Shader",
        "IGP (true/false)", "Bus", "Memory Type", "GPU Chip"
    };

    JTextField[] fields = new JTextField[labels.length];
    for (int i = 0; i < labels.length; i++) {
        panel.add(new JLabel(labels[i] + ":"));
        String currentValue = table.getValueAt(selectedRow, i).toString();
        fields[i] = new JTextField(currentValue);
        panel.add(fields[i]);
    }

    int result = JOptionPane.showConfirmDialog(this, panel, "Sửa thông tin card đồ họa", JOptionPane.OK_CANCEL_OPTION);
    if (result == JOptionPane.OK_OPTION) {
        try {
            String[] newData = new String[labels.length];
            for (int i = 0; i < labels.length; i++) {
                String input = fields[i].getText().trim();

                // Giữ lại Manufacturer và Product Name nếu để trống
                if ((i == 0 || i == 1) && input.isEmpty()) {
                    newData[i] = table.getValueAt(selectedRow, i).toString().trim();
                } else {
                    newData[i] = input;
                }

                // Kiểm tra bỏ trống (trừ Unified Shader, Pixel Shader, Vertex Shader: 7, 10, 11)
                if (i != 7 && i != 10 && i != 11 && newData[i].isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" không được bỏ trống!");
                    return;
                }

                // Kiểm tra kiểu dữ liệu
                if (!newData[i].isEmpty()) {
                    if (i == 3) { // Memory Size
                        try {
                            Double.parseDouble(newData[i]);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" phải là số thực!");
                            return;
                        }
                    } else if (i >= 2 && i <= 11 && i != 3 && i != 12) {
                        try {
                            Integer.parseInt(newData[i]);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" phải là số nguyên!");
                            return;
                        }
                    } else if (i == 12) { // IGP
                        if (newData[i].equalsIgnoreCase("true")) {
                            newData[i] = "Yes";
                        } else if (newData[i].equalsIgnoreCase("false")) {
                            newData[i] = "No";
                        } else {
                            JOptionPane.showMessageDialog(this, "Trường \"" + labels[i] + "\" chỉ được nhập true hoặc false!");
                            return;
                        }
                    }
                }
            }

            // Xóa node cũ khỏi cây AVL
            String oldReleaseYearStr = table.getValueAt(selectedRow, 2).toString().trim();
            int oldReleaseYear = Integer.parseInt(oldReleaseYearStr);
            tree.delete(oldReleaseYear);

            // Thêm node mới vào cây AVL
GraphicsCard newCard = new GraphicsCard(newData);
tree.insert(newCard);

// 👉 Sắp xếp lại bảng dựa trên cây AVL
List<GraphicsCard> sortedCards = tree.layDanhSachCardTheoNamGiamDan();
DefaultTableModel model = (DefaultTableModel) table.getModel();
model.setRowCount(0); // xóa toàn bộ dòng cũ

for (GraphicsCard card : sortedCards) {
    model.addRow(new Object[] {
        card.manufacturer,
        card.productName,
        card.releaseYear,
        card.memSize,
        card.memBusWidth,
        card.gpuClock,
        card.memClock,
        card.unifiedShader,
        card.tmu,
        card.rop,
        card.pixelShader,
        card.vertexShader,
        card.igp,
        card.bus,
        card.memType,
        card.gpuChip
    });
}


            JOptionPane.showMessageDialog(this, "Đã sửa thông tin card đồ họa!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_bthSuaActionPerformed

    private void btnSapxeptheoCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxeptheoCardActionPerformed

// Tạo cây mới tổ chức theo tên sản phẩm
    AVLTreetheoTenCard cayTheoTen = new AVLTreetheoTenCard();

    // Chèn toàn bộ card từ cây gốc (theo năm) vào cây mới (theo tên)
    List<GraphicsCard> danhSachGoc = tree.layTatCaCard(); // 'tree' là cây AVL theo releaseYear
    for (GraphicsCard card : danhSachGoc) {
        cayTheoTen.insert(card);
    }

    // Lấy danh sách card theo thứ tự tên sản phẩm tăng dần
    List<GraphicsCard> danhSach = cayTheoTen.layTatCaCard();

    // Hiển thị lại bảng
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // xóa dữ liệu cũ

    for (GraphicsCard card : danhSach) {
        model.addRow(new Object[] {
            card.manufacturer,
            card.productName,
            card.releaseYear,
            card.memSize,
            card.memBusWidth,
            card.gpuClock,
            card.memClock,
            card.unifiedShader,
            card.tmu,
            card.rop,
            card.pixelShader,
            card.vertexShader,
            card.igp,
            card.bus,
            card.memType,
            card.gpuChip
        });
    }

    // Hiển thị thống kê cây theo tên sản phẩm
    GraphicsCard goc = cayTheoTen.getRootCard();
    StringBuilder sb = new StringBuilder();
    sb.append(" Thống kê cây AVL theo tên sản phẩm:\n");
    sb.append("- Node gốc: ").append(goc != null ? goc.productName : "Không có").append("\n");
    sb.append("- Chiều cao cây: ").append(cayTheoTen.getHeight()).append("\n");
    sb.append("- Node có 2 lá: ").append(cayTheoTen.demNodeHaiLa()).append("\n");
    sb.append("- Node có 1 lá: ").append(cayTheoTen.demNodeMotLa()).append("\n");
    sb.append("- Node chỉ có cây con bên trái: ").append(cayTheoTen.demNodeChiTrai()).append("\n");
    sb.append("- Node chỉ có cây con bên phải: ").append(cayTheoTen.demNodeChiPhai()).append("\n");

    JOptionPane.showMessageDialog(this, sb.toString(), "Thống kê cây theo tên sản phẩm", JOptionPane.INFORMATION_MESSAGE);       
    }//GEN-LAST:event_btnSapxeptheoCardActionPerformed

    private void btnSapxeptheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxeptheoTenActionPerformed
// Tạo cây mới tổ chức theo hãng sản xuất
    AVLTreetheoHangCard cayTheoHang = new AVLTreetheoHangCard();

    // Chèn toàn bộ card từ cây gốc (theo năm) vào cây mới (theo hãng)
    List<GraphicsCard> danhSachGoc = tree.layTatCaCard(); // 'tree' là cây AVL theo releaseYear
    for (GraphicsCard card : danhSachGoc) {
        cayTheoHang.insert(card);
    }

    // Lấy danh sách card theo thứ tự hãng sản xuất tăng dần
    List<GraphicsCard> danhSach = cayTheoHang.layTatCaCard();

    // Hiển thị lại bảng
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // xóa dữ liệu cũ

    for (GraphicsCard card : danhSach) {
        model.addRow(new Object[] {
            card.manufacturer,
            card.productName,
            card.releaseYear,
            card.memSize,
            card.memBusWidth,
            card.gpuClock,
            card.memClock,
            card.unifiedShader,
            card.tmu,
            card.rop,
            card.pixelShader,
            card.vertexShader,
            card.igp,
            card.bus,
            card.memType,
            card.gpuChip
        });
    }

    // Hiển thị thống kê cây theo hãng sản xuất
    GraphicsCard goc = cayTheoHang.getRootCard();
    StringBuilder sb = new StringBuilder();
    sb.append(" Thống kê cây AVL theo hãng sản xuất:\n");
    sb.append("- Node gốc: ").append(goc != null ? goc.manufacturer : "Không có").append("\n");
    sb.append("- Chiều cao cây: ").append(cayTheoHang.getHeight()).append("\n");
    sb.append("- Node có 2 lá: ").append(cayTheoHang.demNodeHaiLa()).append("\n");
    sb.append("- Node có 1 lá: ").append(cayTheoHang.demNodeMotLa()).append("\n");
    sb.append("- Node chỉ có cây con bên trái: ").append(cayTheoHang.demNodeChiTrai()).append("\n");
    sb.append("- Node chỉ có cây con bên phải: ").append(cayTheoHang.demNodeChiPhai()).append("\n");

    JOptionPane.showMessageDialog(this, sb.toString(), "Thống kê cây theo hãng sản xuất", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSapxeptheoTenActionPerformed

    private void btnSapxeptheoGPUchipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxeptheoGPUchipActionPerformed
// Tạo cây mới tổ chức theo GPU chip
    AVLTreetheoGPUCard cayTheoGPU = new AVLTreetheoGPUCard();

    // Chèn toàn bộ card từ cây gốc (theo năm) vào cây mới (theo GPU chip)
    List<GraphicsCard> danhSachGoc = tree.layTatCaCard(); // 'tree' là cây AVL theo releaseYear
    for (GraphicsCard card : danhSachGoc) {
        cayTheoGPU.insert(card);
    }

    // Lấy danh sách card theo thứ tự GPU chip tăng dần
    List<GraphicsCard> danhSach = cayTheoGPU.layTatCaCard();

    // Hiển thị lại bảng
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // xóa dữ liệu cũ

    for (GraphicsCard card : danhSach) {
        model.addRow(new Object[] {
            card.manufacturer,
            card.productName,
            card.releaseYear,
            card.memSize,
            card.memBusWidth,
            card.gpuClock,
            card.memClock,
            card.unifiedShader,
            card.tmu,
            card.rop,
            card.pixelShader,
            card.vertexShader,
            card.igp,
            card.bus,
            card.memType,
            card.gpuChip
        });
    }

    // Hiển thị thống kê cây theo GPU chip
    GraphicsCard goc = cayTheoGPU.getRootCard();
    StringBuilder sb = new StringBuilder();
    sb.append(" Thống kê cây AVL theo GPU chip:\n");
    sb.append("- Node gốc: ").append(goc != null ? goc.gpuChip : "Không có").append("\n");
    sb.append("- Chiều cao cây: ").append(cayTheoGPU.getHeight()).append("\n");
    sb.append("- Node có 2 lá: ").append(cayTheoGPU.demNodeHaiLa()).append("\n");
    sb.append("- Node có 1 lá: ").append(cayTheoGPU.demNodeMotLa()).append("\n");
    sb.append("- Node chỉ có cây con bên trái: ").append(cayTheoGPU.demNodeChiTrai()).append("\n");
    sb.append("- Node chỉ có cây con bên phải: ").append(cayTheoGPU.demNodeChiPhai()).append("\n");

    JOptionPane.showMessageDialog(this, sb.toString(), "Thống kê cây theo GPU chip", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSapxeptheoGPUchipActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String luaChon = jComboBox1.getSelectedItem().toString();

    List<GraphicsCard> danhSach = tree.layTatCaCard(); // 'tree' là cây AVL theo releaseYear

    if (luaChon.equals("Sắp xếp tăng dần")) {
        danhSach.sort((a, b) -> Integer.compare(a.releaseYear, b.releaseYear));
    } else if (luaChon.equals("Sắp xếp giảm dần")) {
        danhSach.sort((a, b) -> Integer.compare(b.releaseYear, a.releaseYear));
    }

    // Hiển thị lại bảng
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // xóa dữ liệu cũ

    for (GraphicsCard card : danhSach) {
        model.addRow(new Object[] {
            card.manufacturer,
            card.productName,
            card.releaseYear,
            card.memSize,
            card.memBusWidth,
            card.gpuClock,
            card.memClock,
            card.unifiedShader,
            card.tmu,
            card.rop,
            card.pixelShader,
            card.vertexShader,
            card.igp,
            card.bus,
            card.memType,
            card.gpuChip
        });
    }    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienDocFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthSua;
    private javax.swing.JButton btnChonFile;
    private javax.swing.JButton btnSapxeptheoCard;
    private javax.swing.JButton btnSapxeptheoGPUchip;
    private javax.swing.JButton btnSapxeptheoTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
